In [4]:
import numpy as np
import cv2 as cv2
import os as os

In [7]:
os.listdir()

['.ipynb_checkpoints', 'import_image.ipynb', 'Numpy.ipynb', 'smallgray.png']

In [9]:
image1 = cv2.imread("smallgray.png", 0) #gray scale
image1

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [10]:
image2 = cv2.imread("smallgray.png", 1) #BGR 3d array
image2

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [11]:
cv2.imwrite("newsmallgray.png", image1)

True

In [12]:
a = [1,2,3]
a[0:2]

[1, 2]

In [14]:
image1[0:2] #get first two rows

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [15]:
image1[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [16]:
image1.shape

(3, 5)

In [17]:
# from the above we see that we go in the conventional style of [rows, columns]

In [18]:
# iterate a numpy array
for i in image1:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [20]:
# iterate by column
for i in image1.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [21]:
# all items
for i in image1.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [22]:
for i in image2.flat:
    print(i)

187
187
187
158
158
158
104
104
104
121
121
121
143
143
143
198
198
198
125
125
125
255
255
255
255
255
255
147
147
147
209
209
209
134
134
134
255
255
255
97
97
97
182
182
182
